In [1]:
import pandas

In [3]:
# dataset is laoded  
dataset = pandas.read_csv("marks.csv")

In [4]:
dataset

marks  hours
0      3     30
1      7     70
2      2     20
3      8     80

In [17]:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
x = dataset['marks']
x = x.values.reshape(-1 ,1)


In [18]:
y = dataset['hours']
y = y.values.reshape(-1 , 1)

In [19]:
x

array([[3],
       [7],
       [2],
       [8]], dtype=int64)

In [20]:
y

array([[30],
       [70],
       [20],
       [80]], dtype=int64)

In [14]:
from sklearn.linear_model import LinearRegression

In [21]:
model = LinearRegression()

In [22]:
model.fit(x , y) 

LinearRegression()

In [24]:
model.predict([[9]])

array([[90.]])

In [25]:
model.coef_

array([[10.]])