In [2]:
#Code for Simple linear Regression
import pandas
dataset = pandas.read_csv('SalaryData.csv');
y = dataset['Salary']
x = dataset['YearsExperience']
x = x.values.reshape(-1 , 1)
y = y.values.reshape(-1 , 1)
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(x , y)
model.predict([[2.5]])

array([[49417.10600231]])

In [3]:
model.coef_   # coefficient

array([[9449.96232146]])

In [4]:
model.intercept_

array([25792.20019867])

In [6]:
import joblib
joblib.dump(model,'salary_model.pk1')

['salary_model.pk1']

In [10]:
import joblib
model = joblib.load('salary_model.pk1')
print("Enter your experience: ", end = " ")
exp = float (input())
print("The salary is: " , end = " ")
predicted = model.predict([[exp]])
print(predicted)

Enter your experience:  2.5
The salary is:  [[49417.10600231]]
